modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)

[[mods]]
modId="humandynamics" #mandatory
version="1.0.0
displayName="Human Dynamics"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="humandynamics.jpg" #optional

credits="Thank You! To all of our supporters!"
authors="The HomanoidDynacmics Crew"
description='''
For a HUGE experience with villagers
'''
[[dependencies.humandynamics]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.humandynamics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
